<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="color-scheme" content="dark">
  <title>Spike · Marketing OS</title>
  <style>
    :root{--bg:#0c0c0e;--sidebar:#0a0a0c;--surface:#111114;--surface-2:#151519;--hover:#19191e;--line:#25252b;--line-soft:#1b1b20;--text:#f1f1f3;--muted:#8b8b95;--dim:#5f5f68;--green:#63e28f;--green-soft:rgba(99,226,143,.11);--amber:#e5b85c;--amber-soft:rgba(229,184,92,.10);--purple:#8b7cf6;--radius:8px}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-width:320px;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:13px;-webkit-font-smoothing:antialiased}button,input{font:inherit}button,a{-webkit-tap-highlight-color:transparent}a{color:inherit}.app{min-height:100vh;display:grid;grid-template-columns:220px minmax(0,1fr)}
    .sidebar{position:sticky;top:0;height:100vh;padding:13px 10px;border-right:1px solid var(--line-soft);background:var(--sidebar);display:flex;flex-direction:column}.workspace{height:34px;display:flex;align-items:center;gap:9px;padding:0 8px;margin-bottom:15px}.mark{width:22px;height:22px;border-radius:6px;display:grid;place-items:center;background:linear-gradient(145deg,#83f0a8,#42bd6d);color:#07120a;font-weight:800;font-size:11px;box-shadow:0 0 22px rgba(99,226,143,.14)}.workspace-name{font-weight:600;font-size:13px;letter-spacing:-.01em}.workspace-sub{color:var(--dim);font-size:10px;margin-top:1px}.nav-section{margin:8px 0 4px;padding:0 9px;color:#55555d;font-size:9px;font-weight:650;letter-spacing:.1em;text-transform:uppercase}.nav{display:grid;gap:1px}.nav-btn{height:30px;padding:0 9px;border:0;border-radius:5px;background:transparent;color:#85858f;display:flex;align-items:center;justify-content:space-between;cursor:pointer;text-align:left}.nav-btn:hover{background:#141417;color:#c6c6cc}.nav-btn.active{background:#19191d;color:#f2f2f4}.nav-label{display:flex;align-items:center;gap:9px}.icon{width:14px;color:#65656e;font-size:11px;text-align:center}.nav-btn.active .icon{color:var(--green)}.count{min-width:18px;color:#62626a;font-size:10px;text-align:right}.nav-btn.active .count{color:#a8a8b0}.sidebar-foot{margin-top:auto;padding:11px 8px 4px;border-top:1px solid var(--line-soft)}.live{display:flex;align-items:center;gap:8px;color:#81818a;font-size:10px}.live-dot{width:6px;height:6px;border-radius:50%;background:var(--green);box-shadow:0 0 0 3px var(--green-soft)}.sync{margin-top:7px;color:#505058;font-size:9px;line-height:1.5}
    .main{min-width:0}.topbar{position:sticky;top:0;z-index:10;height:48px;padding:0 24px;border-bottom:1px solid var(--line-soft);background:rgba(12,12,14,.86);backdrop-filter:blur(18px);display:flex;align-items:center;justify-content:space-between;gap:18px}.crumb{display:flex;align-items:center;gap:8px;color:#777780;font-size:11px;white-space:nowrap}.crumb strong{color:#c8c8ce;font-weight:500}.search-wrap{position:relative;width:min(340px,42vw)}.search{width:100%;height:28px;padding:0 52px 0 28px;border:1px solid var(--line);border-radius:6px;background:#121215;color:var(--text);outline:none;font-size:11px}.search:focus{border-color:#44444d;background:#151519;box-shadow:0 0 0 3px rgba(139,124,246,.08)}.search::placeholder{color:#585861}.search-symbol{position:absolute;left:9px;top:6px;color:#575760}.key{position:absolute;right:6px;top:4px;padding:1px 5px;border:1px solid #2a2a30;border-radius:4px;color:#62626b;background:#18181c;font-size:9px}.mobile{display:none;border:0;background:transparent;color:var(--muted);font-size:17px}.content{max-width:1380px;margin:0 auto;padding:26px 30px 70px}.view{display:none}.view.active{display:block;animation:enter .16s ease}@keyframes enter{from{opacity:.5;transform:translateY(2px)}to{opacity:1;transform:none}}
    .page-head{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:20px}.eyebrow{color:#66666f;font-size:9px;text-transform:uppercase;letter-spacing:.12em}.page-title{margin:5px 0 5px;font-size:20px;line-height:1.25;letter-spacing:-.025em;font-weight:580}.page-sub{margin:0;color:#777780;font-size:11px;line-height:1.55;max-width:650px}.date{padding-top:4px;color:#5d5d66;font-size:10px;white-space:nowrap}.section{margin-top:24px}.section-head{height:30px;display:flex;align-items:center;justify-content:space-between;gap:12px}.section-title{margin:0;font-size:12px;font-weight:560;color:#d2d2d7}.section-note{color:#5f5f68;font-size:10px}
    .focus{border:1px solid var(--line);border-radius:var(--radius);background:linear-gradient(105deg,#151519 0%,#111114 65%);overflow:hidden}.focus-top{padding:18px 20px 15px;border-bottom:1px solid var(--line-soft)}.focus-label{display:flex;align-items:center;gap:7px;color:var(--green);font-size:9px;text-transform:uppercase;letter-spacing:.1em}.focus-label:before{content:"";width:5px;height:5px;border-radius:50%;background:var(--green)}.focus h2{margin:10px 0 6px;font-size:22px;line-height:1.25;font-weight:540;letter-spacing:-.035em;max-width:850px}.focus p{margin:0;color:#7d7d86;line-height:1.6;font-size:11px;max-width:800px}.metrics{display:grid;grid-template-columns:repeat(4,1fr)}.metric{min-height:74px;padding:13px 16px;border-right:1px solid var(--line-soft)}.metric:last-child{border-right:0}.metric-label{color:#62626b;font-size:9px;text-transform:uppercase;letter-spacing:.07em}.metric-value{margin-top:8px;font-size:18px;letter-spacing:-.03em}.metric-note{margin-top:2px;color:#55555d;font-size:9px}
    .split{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(300px,.75fr);gap:12px}.panel{border:1px solid var(--line);border-radius:var(--radius);background:var(--surface);overflow:hidden}.row{min-height:52px;padding:10px 13px;border-bottom:1px solid var(--line-soft);display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.row:last-child{border-bottom:0}.row:hover{background:var(--hover)}.row-main{min-width:0}.row-title{margin:0;color:#d8d8dc;font-size:11px;font-weight:520;line-height:1.4}.row-meta{margin-top:4px;color:#5f5f68;font-size:9px}.row-copy{margin:5px 0 0;color:#777780;font-size:10px;line-height:1.5}.weekly{display:grid;grid-template-columns:72px minmax(0,1fr) auto;align-items:center;gap:10px;min-height:46px;padding:8px 12px;border-bottom:1px solid var(--line-soft)}.weekly:last-child{border-bottom:0}.weekly:hover{background:var(--hover)}.weekly-day{color:#65656e;font-size:9px}.weekly-title{color:#cfcfd4;font-size:10px}.weekly-sub{margin-top:3px;color:#575760;font-size:9px}
    .badge{display:inline-flex;align-items:center;padding:2px 6px;border:1px solid #2b2b31;border-radius:4px;background:#18181c;color:#797982;font-size:8px;text-transform:uppercase;letter-spacing:.05em;white-space:nowrap}.badge.pending{border-color:rgba(229,184,92,.22);background:var(--amber-soft);color:#cba757}.badge.done{border-color:rgba(99,226,143,.18);background:var(--green-soft);color:#71d996}.badge.selected{border-color:rgba(139,124,246,.25);background:rgba(139,124,246,.1);color:#a69cf6}.toolbar{min-height:36px;margin-bottom:8px;display:flex;align-items:center;justify-content:space-between;gap:10px}.filters{display:flex;gap:4px;flex-wrap:wrap}.filter,.button{height:26px;padding:0 9px;border:1px solid var(--line);border-radius:5px;background:#121215;color:#777780;font-size:9px;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center}.filter:hover,.button:hover{background:#1a1a1e;color:#d0d0d5}.filter.active{background:#202025;color:#e5e5e8;border-color:#33333a}.button.primary{border-color:#3a3a42;background:#ededf0;color:#161619}.button.green{border-color:rgba(99,226,143,.18);background:var(--green-soft);color:#79df9c}
    .cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.card{min-width:0;padding:14px;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface)}.card:hover{border-color:#34343b;background:#131317}.card-top{display:flex;align-items:center;justify-content:space-between;gap:10px;color:#5d5d65;font-size:9px}.card h3{margin:12px 0 6px;color:#dadade;font-size:13px;line-height:1.35;font-weight:560;letter-spacing:-.01em}.card p{margin:0;color:#74747d;font-size:10px;line-height:1.55}.detail{margin-top:11px;padding-top:10px;border-top:1px solid var(--line-soft)}.detail strong{display:block;margin-bottom:4px;color:#a5a5ad;font-size:9px;font-weight:550}.actions{display:flex;align-items:center;gap:5px;flex-wrap:wrap;margin-top:12px}.approval{border-left:2px solid var(--amber)}.warning{margin-top:10px;padding:8px 9px;border-radius:5px;background:var(--amber-soft);color:#b99a58;font-size:9px;line-height:1.45}
    .table-wrap{overflow:auto;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface)}table{width:100%;border-collapse:collapse;min-width:760px}th{height:30px;padding:0 11px;border-bottom:1px solid var(--line);background:#131316;color:#5f5f68;text-align:left;font-size:8px;text-transform:uppercase;letter-spacing:.07em;font-weight:600}td{padding:9px 11px;border-bottom:1px solid var(--line-soft);color:#74747d;font-size:9px;line-height:1.5;vertical-align:top}tbody tr:hover{background:#17171b}tr:last-child td{border-bottom:0}td strong{color:#cfcfd4;font-weight:520}
    .calendar-bar{min-height:36px;display:flex;align-items:center;justify-content:space-between;gap:12px}.calendar-month{color:#d7d7dc;font-size:12px;font-weight:560;text-transform:capitalize}.calendar-controls{display:flex;gap:4px}.calendar-weekdays,.calendar{display:grid;grid-template-columns:repeat(7,minmax(108px,1fr));gap:5px;min-width:780px}.calendar-wrap{overflow:auto}.calendar-weekdays{margin-bottom:5px}.weekday{padding:0 8px;color:#55555e;font-size:8px;text-transform:uppercase;letter-spacing:.07em}.calendar-day{min-height:112px;padding:8px;border:1px solid var(--line);border-radius:6px;background:var(--surface)}.calendar-day.other{opacity:.34}.calendar-day.today{border-color:rgba(99,226,143,.48);box-shadow:inset 0 0 0 1px rgba(99,226,143,.08)}.day-number{color:#8d8d96;font-size:10px}.calendar-day.today .day-number{color:var(--green)}.event{width:100%;margin-top:7px;padding:6px;border:0;border-left:2px solid var(--green);border-radius:3px;background:var(--green-soft);color:#87dca2;font:inherit;font-size:8px;line-height:1.4;text-align:left}.event[data-open-draft]{cursor:pointer}.event[data-open-draft]:hover{background:rgba(99,226,143,.18)}.event strong{display:block;margin-bottom:2px;color:#bceaca;font-weight:550}.clickable-row{cursor:pointer}.clickable-row:focus{outline:1px solid rgba(99,226,143,.55);outline-offset:-2px}.timeline{position:relative;padding-left:17px}.timeline:before{content:"";position:absolute;left:3px;top:8px;bottom:8px;width:1px;background:var(--line)}.timeline-item{position:relative;padding:0 0 18px 8px}.timeline-item:before{content:"";position:absolute;left:-17px;top:4px;width:7px;height:7px;border-radius:50%;background:var(--bg);border:1px solid var(--green)}.timeline-date{color:#55555e;font-size:8px;text-transform:uppercase}.timeline-title{margin-top:5px;color:#d2d2d7;font-size:11px}.timeline-copy{margin-top:4px;color:#72727b;font-size:10px;line-height:1.5}.empty{padding:28px 18px;text-align:center;color:#56565f;font-size:10px}.empty strong{display:block;margin-bottom:5px;color:#898992;font-size:11px}.error{margin:20px;padding:16px;border:1px solid rgba(229,100,100,.35);border-radius:8px;background:rgba(229,100,100,.08);color:#e6a2a2}.toast{position:fixed;right:20px;bottom:20px;padding:8px 11px;border:1px solid #34343b;border-radius:6px;background:#1d1d22;color:#d8d8dd;font-size:10px;opacity:0;transform:translateY(6px);pointer-events:none;transition:.15s}.toast.show{opacity:1;transform:none}
    .modal[hidden]{display:none}.modal{position:fixed;inset:0;z-index:60;display:grid;place-items:center;padding:22px}.modal-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.72);backdrop-filter:blur(5px)}.modal-panel{position:relative;width:min(920px,100%);max-height:min(90vh,900px);display:flex;flex-direction:column;border:1px solid #303038;border-radius:10px;background:#111114;box-shadow:0 30px 90px rgba(0,0,0,.65);overflow:hidden}.modal-head{padding:15px 17px;border-bottom:1px solid var(--line);display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.modal-kicker{color:var(--green);font-size:8px;text-transform:uppercase;letter-spacing:.1em}.modal-title{margin:5px 0 0;font-size:17px;font-weight:570;letter-spacing:-.02em}.modal-close{width:26px;height:26px;border:1px solid var(--line);border-radius:5px;background:#17171b;color:#8d8d96;cursor:pointer}.modal-body{padding:18px;overflow:auto;color:#a0a0a9;font-size:11px;line-height:1.65}.modal-body h2{margin:22px 0 8px;color:#ededf0;font-size:14px}.modal-body h3{margin:17px 0 6px;color:#d2d2d8;font-size:12px}.modal-body p{margin:0 0 9px}.modal-body ul{margin:4px 0 12px;padding-left:18px}.modal-body strong{color:#d1d1d6;font-weight:560}.modal-section-title{margin:0 0 10px!important;color:#8b8b95!important;font-size:9px!important;text-transform:uppercase;letter-spacing:.1em}.editorial-doc{margin-top:22px;padding-top:2px;border-top:1px solid var(--line)}.case-detail{display:grid;gap:12px}.case-field{padding:11px 12px;border:1px solid var(--line-soft);border-radius:6px;background:#151519}.case-field span{display:block;margin-bottom:4px;color:#5f5f68;font-size:8px;text-transform:uppercase;letter-spacing:.07em}.case-field p{margin:0;color:#aaaab2}.render-strip{display:flex;gap:6px;margin-top:12px;overflow:hidden}.render-thumb{width:72px;aspect-ratio:4/5;object-fit:cover;border:1px solid var(--line);border-radius:5px;background:#0a0a0c}.render-placeholder{height:90px;margin-top:12px;display:grid;place-items:center;border:1px dashed #303038;border-radius:6px;color:#5f5f68;font-size:9px}.visual-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.visual-frame{margin:0}.visual-frame img{display:block;width:100%;height:auto;border:1px solid var(--line);border-radius:7px;background:white}.visual-frame figcaption{padding-top:5px;color:#62626b;font-size:9px;text-align:center}
    @media(max-width:1050px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.split{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.metric:nth-child(2){border-right:0}.metric:nth-child(-n+2){border-bottom:1px solid var(--line-soft)}}
    @media(max-width:720px){.app{display:block}.sidebar{position:fixed;inset:0 auto 0 0;width:220px;z-index:30;transform:translateX(-102%);transition:.18s;box-shadow:20px 0 50px rgba(0,0,0,.5)}.sidebar.open{transform:none}.mobile{display:block}.topbar{padding:0 14px}.crumb{display:none}.search-wrap{width:100%}.content{padding:20px 14px 55px}.page-head{flex-direction:column;gap:8px}.date{display:none}.cards{grid-template-columns:1fr}.metrics{grid-template-columns:1fr}.metric{border-right:0;border-bottom:1px solid var(--line-soft)}.metric:last-child{border-bottom:0}}
  </style>
</head>
<body>
  <script id="dashboard-data" type="application/json">__DASHBOARD_DATA__</script>
  <div class="app">
    <aside class="sidebar" id="sidebar">
      <div class="workspace"><div class="mark">S</div><div><div class="workspace-name">Spike</div><div class="workspace-sub">Marketing OS</div></div></div>
      <div class="nav-section">Workspace</div>
      <nav class="nav">
        <button class="nav-btn active" data-view="overview"><span class="nav-label"><span class="icon">⌂</span>Resumen</span></button>
        <button class="nav-btn" data-view="activity"><span class="nav-label"><span class="icon">◷</span>Actividad</span><span class="count" id="nav-activity">—</span></button>
        <button class="nav-btn" data-view="research"><span class="nav-label"><span class="icon">⌕</span>Investigación</span><span class="count" id="nav-research">—</span></button>
        <button class="nav-btn" data-view="ideas"><span class="nav-label"><span class="icon">◇</span>Ideas</span><span class="count" id="nav-ideas">—</span></button>
        <div class="nav-section">Producción</div>
        <button class="nav-btn" data-view="approvals"><span class="nav-label"><span class="icon">✓</span>Aprobaciones</span><span class="count" id="nav-approvals">—</span></button>
        <button class="nav-btn" data-view="production"><span class="nav-label"><span class="icon">◫</span>Producción</span><span class="count" id="nav-production">—</span></button>
        <button class="nav-btn" data-view="library"><span class="nav-label"><span class="icon">▤</span>Biblioteca</span><span class="count" id="nav-library">—</span></button>
        <button class="nav-btn" data-view="calendar"><span class="nav-label"><span class="icon">□</span>Calendario</span></button>
      </nav>
      <div class="sidebar-foot"><div class="live"><span class="live-dot"></span>Datos locales conectados</div><div class="sync" id="sidebar-sync">Cargando…</div></div>
    </aside>
    <main class="main">
      <header class="topbar"><button class="mobile" id="mobile-toggle" aria-label="Abrir navegación">☰</button><div class="crumb"><span>Spike</span><span>/</span><strong id="crumb">Resumen</strong></div><div class="search-wrap"><span class="search-symbol">⌕</span><input class="search" id="global-search" type="search" placeholder="Buscar en el sistema…"><span class="key">/</span></div></header>
      <div class="content" id="content">
        <section class="view active" id="view-overview"><div class="page-head"><div><div class="eyebrow">Control room</div><h1 class="page-title">Marketing, sin ruido</h1><p class="page-sub">Estado editorial de Spike, generado directamente desde los archivos del sistema.</p></div><div class="date" id="overview-date"></div></div><div id="overview-content"></div></section>
        <section class="view" id="view-activity"><div class="page-head"><div><div class="eyebrow">Registro</div><h1 class="page-title">Actividad</h1><p class="page-sub">Todo lo que hizo el agente y qué archivos modificó.</p></div><div class="date" id="activity-total"></div></div><div class="panel"><div class="timeline" id="activity-list" style="padding:16px 17px 2px 30px"></div></div></section>
        <section class="view" id="view-research"><div class="page-head"><div><div class="eyebrow">Inteligencia</div><h1 class="page-title">Investigación</h1><p class="page-sub">Hallazgos aceptados y su implicancia concreta para Spike.</p></div></div><div class="cards" id="research-grid"></div></section>
        <section class="view" id="view-ideas"><div class="page-head"><div><div class="eyebrow">Pipeline</div><h1 class="page-title">Ideas de contenido</h1><p class="page-sub">Backlog priorizado con evidencia, valor y estado editorial.</p></div><div class="date" id="ideas-count"></div></div><div class="toolbar"><div class="filters" id="idea-filters"><button class="filter active" data-filter="all">Todas</button><button class="filter" data-filter="seleccionado">Seleccionadas</button><button class="filter" data-filter="backlog">Backlog</button></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Idea</th><th>Pilar</th><th>Evidencia</th><th>Valor</th><th>Estado</th></tr></thead><tbody id="ideas-table"></tbody></table></div></section>
        <section class="view" id="view-approvals"><div class="page-head"><div><div class="eyebrow">Tu decisión</div><h1 class="page-title">Por aprobar</h1><p class="page-sub">Nada se publica sin revisión humana.</p></div><div class="date" id="approval-count"></div></div><div class="cards" id="approvals-grid"></div></section>
        <section class="view" id="view-production"><div class="page-head"><div><div class="eyebrow">Taller visual</div><h1 class="page-title">Producción</h1><p class="page-sub">Fuentes HTML/CSS, renders finales y segunda aprobación antes de publicar.</p></div><div class="date" id="production-count"></div></div><div class="cards" id="production-grid"></div></section>
        <section class="view" id="view-library"><div class="page-head"><div><div class="eyebrow">Archivo</div><h1 class="page-title">Biblioteca</h1><p class="page-sub">Piezas, publicaciones y casos anónimos reutilizables.</p></div></div><div class="toolbar"><div class="filters" id="library-filters"><button class="filter active" data-library="drafts">Piezas</button><button class="filter" data-library="published">Publicadas</button><button class="filter" data-library="cases">Casos</button></div></div><div class="cards" id="library-grid"></div></section>
        <section class="view" id="view-calendar"><div class="page-head"><div><div class="eyebrow">Cadencia</div><h1 class="page-title">Calendario</h1><p class="page-sub">Vista mensual completa de lo previsto y su objetivo.</p></div></div><div class="calendar-bar"><div class="calendar-month" id="calendar-month"></div><div class="calendar-controls"><button class="button" id="calendar-prev" aria-label="Mes anterior">←</button><button class="button" id="calendar-today">Mes del plan</button><button class="button" id="calendar-next" aria-label="Mes siguiente">→</button></div></div><div class="calendar-wrap"><div class="calendar-weekdays"><div class="weekday">Lun</div><div class="weekday">Mar</div><div class="weekday">Mié</div><div class="weekday">Jue</div><div class="weekday">Vie</div><div class="weekday">Sáb</div><div class="weekday">Dom</div></div><div class="calendar" id="calendar-grid"></div></div><div class="section"><div class="section-head"><h2 class="section-title">Plan completo</h2></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>ID</th><th>Tema</th><th>Formato</th><th>Objetivo</th><th>CTA</th><th>Estado</th></tr></thead><tbody id="calendar-table"></tbody></table></div></div></section>
      </div>
    </main>
  </div>
  <div class="toast" id="toast">Copiado</div>
  <div class="modal" id="detail-modal" hidden><div class="modal-backdrop" data-close-modal></div><section class="modal-panel" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><div><div class="modal-kicker" id="modal-kicker"></div><h2 class="modal-title" id="modal-title"></h2></div><button class="modal-close" data-close-modal aria-label="Cerrar">×</button></header><div class="modal-body" id="modal-body"></div></section></div>
  <script>
    (()=>{
      'use strict';
      const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
      const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
      const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[.]$/,'');
      const empty=(a,b)=>`<div class="empty"><strong>${esc(a)}</strong>${esc(b)}</div>`;
      let data; try{data=JSON.parse($('#dashboard-data').textContent)}catch(error){$('#content').innerHTML=`<div class="error"><strong>No se pudieron leer los datos.</strong><br>${esc(error.message)}</div>`;return}
      let query='',ideaFilter='all',libraryFilter='drafts';
      const scheduledDates=(data.calendar||[]).map(x=>new Date(`${x.Fecha}T12:00:00`)).filter(x=>!Number.isNaN(x.valueOf()));
      const planHome=scheduledDates.length?new Date(Math.min(...scheduledDates.map(x=>x.valueOf()))):new Date(`${data.meta.today}T12:00:00`);
      let calendarCursor=new Date(planHome.getFullYear(),planHome.getMonth(),1);
      const matches=(...values)=>!query||norm(values.join(' ')).includes(norm(query));
      const badge=v=>{const n=norm(v),cl=/pendiente|revision/.test(n)?'pending':/complet|aprobad|publicad|aceptad/.test(n)?'done':/seleccionado/.test(n)?'selected':'';return `<span class="badge ${cl}">${esc(v||'sin estado')}</span>`};
      const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};
      const draftFor=id=>data.drafts.find(x=>norm(x.id)===norm(id))||{};
      const markdown=raw=>String(raw||'').split(/\r?\n/).filter(line=>!/^\s*<!--/.test(line)&&!/^#\s/.test(line)).map(line=>{const safe=esc(line).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`(.+?)`/g,'<strong>$1</strong>');if(/^##\s/.test(line))return `<h2>${safe.replace(/^##\s/,'')}</h2>`;if(/^###\s/.test(line))return `<h3>${safe.replace(/^###\s/,'')}</h3>`;if(/^[-*]\s/.test(line))return `<p>• ${safe.replace(/^[-*]\s/,'')}</p>`;return line.trim()?`<p>${safe}</p>`:''}).join('');
      function showModal(kicker,title,body){set('modal-kicker',kicker);set('modal-title',title);$('#modal-body').innerHTML=body;$('#detail-modal').hidden=false;document.body.style.overflow='hidden';$('.modal-close').focus()}
      function closeModal(){$('#detail-modal').hidden=true;document.body.style.overflow=''}
      function openDraft(id){const d=draftFor(id);if(!d.id)return;const production=(data.production||[]).find(x=>norm(x.id)===norm(id)),renders=production?.renders||[];const visual=renders.length?`<section><h3 class="modal-section-title">Visuales · ${renders.length} slides</h3><div class="visual-gallery">${renders.map((render,index)=>`<figure class="visual-frame"><img src="${render.data}" alt="${esc(d.title)} · slide ${index+1}"><figcaption>${esc(render.name)}</figcaption></figure>`).join('')}</div></section>`:'';const editorial=`<section class="editorial-doc"><h3 class="modal-section-title">Detalle editorial</h3>${markdown(d.document)}</section>`;showModal(`${d.id} · ${d.format||'Pieza'}`,d.title,visual+editorial)}
      function openCase(id){const c=data.cases.find(x=>norm(x.id)===norm(id));if(!c)return;const fields=[['Rubro',c.industry],['Problema',c.problem],['Intervención',c.intervention],['Flujo',c.flow],['Capacidades demostradas',c.capabilities],['Resultado aprobado',c.result],['Ángulos posibles',c.angles]];showModal(`${c.id} · Caso anónimo`,c.title,`<div class="case-detail">${fields.filter(x=>x[1]).map(x=>`<div class="case-field"><span>${esc(x[0])}</span><p>${esc(x[1])}</p></div>`).join('')}</div>`)}
      function openIdea(id){const d=draftFor(id);if(d.id){openDraft(id);return}const idea=data.backlog.find(x=>norm(x.ID)===norm(id));if(!idea)return;const fields=[['Pilar',idea.Pilar],['Evidencia',idea.Evidencia],['Valor',`${idea.Valor}/5`],['Autoridad',`${idea.Autoridad}/5`],['Originalidad',`${idea.Originalidad}/5`],['Esfuerzo',`${idea.Esfuerzo}/5`],['Estado',idea.Estado]];showModal(`${idea.ID} · Idea`,idea.Idea,`<div class="case-detail">${fields.filter(x=>x[1]).map(x=>`<div class="case-field"><span>${esc(x[0])}</span><p>${esc(x[1])}</p></div>`).join('')}</div>`)}
      const stageLabel=value=>({produccion:'En producción',revision_visual:'Revisión visual',cambios_visuales:'Cambios solicitados',lista_para_publicar:'Lista para publicar',publicada:'Publicada'})[value]||String(value||'').replaceAll('_',' ');
      function openProduction(id){const item=data.production.find(x=>norm(x.id)===norm(id));if(!item)return;const gallery=item.renders.length?`<div class="visual-gallery">${item.renders.map((render,index)=>`<figure class="visual-frame"><img src="${render.data}" alt="${esc(item.title)} · ${index+1}"><figcaption>${esc(render.name)}</figcaption></figure>`).join('')}</div>`:empty('Todavía no hay renders','La pieza está en producción HTML/CSS.');showModal(`${item.id} · V${item.version} · ${stageLabel(item.stage)}`,item.title,gallery)}
      function overview(){
        const today=(data.todayActivity?.length?data.todayActivity:data.activity).slice(0,6), weekly=data.weekly||[];
        $('#overview-content').innerHTML=`<div class="focus"><div class="focus-top"><div class="focus-label">Próximo hito</div><h2>${esc(data.state.next||'El sistema está listo para producir.')}</h2><p>Spike acompaña a cada empresa desde donde está: preparación, capacitación, reporting, automatización, IA aplicada o desarrollo a medida.</p></div><div class="metrics"><div class="metric"><div class="metric-label">Por aprobar</div><div class="metric-value">${data.summary.pendingApprovals}</div><div class="metric-note">requieren tu decisión</div></div><div class="metric"><div class="metric-label">Ideas</div><div class="metric-value">${data.summary.ideas}</div><div class="metric-note">${data.summary.selectedIdeas} seleccionadas</div></div><div class="metric"><div class="metric-label">Hallazgos</div><div class="metric-value">${data.summary.research}</div><div class="metric-note">investigación aceptada</div></div><div class="metric"><div class="metric-label">Casos</div><div class="metric-value">${data.summary.cases}</div><div class="metric-note">anónimos disponibles</div></div></div></div><div class="section split"><div><div class="section-head"><h2 class="section-title">Plan de la semana</h2><span class="section-note">${weekly.length} piezas</span></div><div class="panel">${weekly.length?weekly.map(x=>`<div class="weekly"><span class="weekly-day">${esc(x['Día'])}</span><div><div class="weekly-title">${esc(x.Pieza)} · ${esc(x.Pilar)}</div><div class="weekly-sub">${esc(x.Formato)} · ${esc(x.Objetivo)}</div></div>${badge(x.Estado)}</div>`).join(''):empty('Sin plan','Todavía no hay una semana planificada.')}</div></div><div><div class="section-head"><h2 class="section-title">Actividad reciente</h2><span class="section-note">${today.length} eventos</span></div><div class="panel">${today.length?today.map(x=>`<div class="row"><div class="row-main"><h3 class="row-title">${esc(x.title)}</h3><div class="row-meta">${esc(x.time)} · ${esc(x.type)}</div><p class="row-copy">${esc(x.summary)}</p></div>${badge(x.status)}</div>`).join(''):empty('Sin actividad','El próximo movimiento aparecerá acá.')}</div></div></div>`;
      }
      function activity(){const rows=data.activity.filter(x=>matches(x.title,x.summary,x.type,x.files));set('activity-total',`${rows.length} registros`);$('#activity-list').innerHTML=rows.length?rows.map(x=>`<article class="timeline-item"><div class="timeline-date">${esc(x.date)} · ${esc(x.time)} · ${esc(x.type)}</div><div class="timeline-title">${esc(x.title)}</div><div class="timeline-copy">${esc(x.summary)}</div>${x.files?`<div class="timeline-copy">Archivos · ${esc(x.files)}</div>`:''}</article>`).join(''):empty('Sin resultados','No hay actividad que coincida.')}
      function research(){const rows=data.research.filter(x=>matches(x.title,x.source,x.evidence,x.implication));$('#research-grid').innerHTML=rows.length?rows.map(x=>`<article class="card"><div class="card-top"><span>${esc(x.id)}</span>${badge(x.status)}</div><h3>${esc(x.title)}</h3><p>${esc(x.evidence)}</p><div class="detail"><strong>Qué significa para Spike</strong><p>${esc(x.implication)}</p></div><div class="actions">${x.url?`<a class="button" href="${esc(x.url)}" target="_blank" rel="noreferrer">Abrir fuente</a>`:''}<span class="badge">${esc(x.source)}</span></div></article>`).join(''):empty('Sin resultados','No hay hallazgos que coincidan.')}
      function ideas(){const rows=data.backlog.filter(x=>(ideaFilter==='all'||norm(x.Estado)===ideaFilter)&&matches(...Object.values(x)));set('ideas-count',`${rows.length} de ${data.backlog.length}`);$('#ideas-table').innerHTML=rows.length?rows.map(x=>`<tr class="clickable-row" data-open-idea="${esc(x.ID)}" tabindex="0" role="button" aria-label="Abrir ${esc(x.Idea)}"><td><strong>${esc(x.ID)}</strong></td><td><strong>${esc(x.Idea)}</strong></td><td>${esc(x.Pilar)}</td><td>${esc(x.Evidencia)}</td><td>${esc(x.Valor)}/5</td><td>${badge(x.Estado)}</td></tr>`).join(''):`<tr><td colspan="6">${empty('Sin ideas','No hay resultados para este filtro.')}</td></tr>`}
      function approvals(){const rows=data.approvals.filter(x=>/pendiente|^$/.test(norm(x['Decisión']))&&matches(...Object.values(x)));set('approval-count',`${rows.length} pendientes`);$('#approvals-grid').innerHTML=rows.length?rows.map(x=>{const d=draftFor(x.ID);return `<article class="card approval"><div class="card-top"><span>${esc(x.ID)} · V${esc(x['Versión'])}</span>${badge(x['Decisión'])}</div><h3>${esc(x.Pieza)}</h3><p>${esc(d.message||d.objective||'Pieza lista para revisión.')}</p><div class="warning">Pendiente · ${esc(x['Riesgos/pendientes'])}</div>${d.caption?`<div class="detail"><strong>Vista del caption</strong><p>${esc(d.caption)}</p></div>`:''}<div class="actions">${d.id?`<button class="button primary" data-open-draft="${esc(d.id)}">Abrir pieza</button>`:''}<button class="button green" data-copy="approve" data-id="${esc(x.ID)}">Copiar aprobación</button><button class="button" data-copy="changes" data-id="${esc(x.ID)}">Pedir cambios</button></div></article>`}).join(''):empty('Todo revisado','No hay piezas esperando aprobación.')}
      function production(){const rows=(data.production||[]).filter(x=>matches(x.id,x.title,x.stage));set('production-count',`${rows.length} piezas`);$('#production-grid').innerHTML=rows.length?rows.map(x=>`<article class="card"><div class="card-top"><span>${esc(x.id)} · V${esc(x.version)}</span>${badge(stageLabel(x.stage))}</div><h3>${esc(x.title)}</h3><p>${esc(x.kind)} · ${esc(x.width)}×${esc(x.height)} · ${x.renders.length} renders</p>${x.renders.length?`<div class="render-strip">${x.renders.slice(0,6).map((render,index)=>`<img class="render-thumb" src="${render.data}" alt="Slide ${index+1}">`).join('')}</div>`:`<div class="render-placeholder">Fuente HTML/CSS en preparación</div>`}<div class="actions"><button class="button primary" data-open-production="${esc(x.id)}">Ver visuales</button>${x.stage==='revision_visual'?`<button class="button green" data-copy="visual-approve" data-id="${esc(x.id)}">Copiar aprobación visual</button><button class="button" data-copy="visual-changes" data-id="${esc(x.id)}">Pedir cambios</button>`:''}</div></article>`).join(''):empty('Sin piezas en producción','Cuando apruebes editorialmente una pieza aparecerá acá.')}
      function library(){let rows;if(libraryFilter==='cases'){rows=data.cases.filter(x=>matches(...Object.values(x)));$('#library-grid').innerHTML=rows.length?rows.map(x=>`<article class="card"><div class="card-top"><span>${esc(x.id)}</span><span class="badge">Caso anónimo</span></div><h3>${esc(x.title)}</h3><p>${esc(x.problem)}</p><div class="detail"><strong>Resultado cualitativo</strong><p>${esc(x.result)}</p></div><div class="actions"><button class="button" data-open-case="${esc(x.id)}">Abrir caso</button><span class="badge">${esc(x.industry)}</span></div></article>`).join(''):empty('Sin casos','No hay coincidencias.');return}if(libraryFilter==='published'){rows=data.published.filter(x=>matches(...Object.values(x)));$('#library-grid').innerHTML=rows.length?rows.map(x=>`<article class="card"><div class="card-top"><span>${esc(x.ID)}</span><span>${esc(x.Fecha)}</span></div><h3>${esc(x.Formato||'Publicación')}</h3><p>${esc(x.Objetivo)}</p></article>`).join(''):empty('Sin publicaciones','Aparecerán acá cuando se publiquen.');return}rows=data.drafts.filter(x=>matches(...Object.values(x)));$('#library-grid').innerHTML=rows.length?rows.map(x=>`<article class="card"><div class="card-top"><span>${esc(x.id)}</span>${badge(x.status)}</div><h3>${esc(x.title)}</h3><p>${esc(x.message||x.objective)}</p><div class="detail"><strong>${esc(x.format)}</strong><p>${esc(x.caption)}</p></div><div class="actions"><button class="button primary" data-open-draft="${esc(x.id)}">Abrir pieza</button><span class="badge">${esc(x.pillar)}</span></div></article>`).join(''):empty('Sin piezas','No hay coincidencias.')}
      function calendar(){const rows=data.calendar||[],first=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));const monthLabel=new Intl.DateTimeFormat('es-UY',{month:'long',year:'numeric'}).format(first);set('calendar-month',monthLabel);$('#calendar-grid').innerHTML=Array.from({length:42},(_,i)=>{const day=new Date(start);day.setDate(start.getDate()+i);const iso=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(day.getDate()).padStart(2,'0')}`,events=rows.filter(r=>r.Fecha===iso),other=day.getMonth()!==first.getMonth();return `<div class="calendar-day ${other?'other':''} ${iso===data.meta.today?'today':''}"><div class="day-number">${day.getDate()}</div>${events.map(x=>{const d=draftFor(x.ID);return d.id?`<button class="event" data-open-draft="${esc(x.ID)}"><strong>${esc(x.ID)}</strong>${esc(x.Tema)}<br>${esc(x.Formato)}</button>`:`<div class="event"><strong>${esc(x.ID)}</strong>${esc(x.Tema)}<br>${esc(x.Formato)}</div>`}).join('')}</div>`}).join('');$('#calendar-table').innerHTML=rows.length?rows.map(x=>{const d=draftFor(x.ID);return `<tr ${d.id?`class="clickable-row" data-open-draft="${esc(x.ID)}" tabindex="0" role="button"`:''}><td><strong>${esc(x.Fecha)}</strong></td><td>${esc(x.ID)}</td><td><strong>${esc(x.Tema)}</strong></td><td>${esc(x.Formato)}</td><td>${esc(x.Objetivo)}</td><td>${esc(x.CTA)}</td><td>${badge(x.Estado)}</td></tr>`}).join(''):`<tr><td colspan="7">Sin contenido programado.</td></tr>`}
      function render(){overview();activity();research();ideas();approvals();production();library();calendar();set('nav-activity',data.activity.length);set('nav-research',data.research.length);set('nav-ideas',data.backlog.length);set('nav-approvals',data.summary.pendingApprovals);set('nav-production',(data.production||[]).length);set('nav-library',data.drafts.length+data.published.length+data.cases.length);set('sidebar-sync',`Actualizado ${data.meta.generatedLabel}`);set('overview-date',data.meta.generatedLabel)}
      function jump(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===name));set('crumb',({overview:'Resumen',activity:'Actividad',research:'Investigación',ideas:'Ideas',approvals:'Aprobaciones',production:'Producción',library:'Biblioteca',calendar:'Calendario'})[name]);$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
      async function copy(text){try{await navigator.clipboard.writeText(text)}catch(_){const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}const t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
      document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n)jump(n.dataset.view);const f=e.target.closest('[data-filter]');if(f){ideaFilter=f.dataset.filter;$$('#idea-filters .filter').forEach(x=>x.classList.toggle('active',x===f));ideas()}const l=e.target.closest('[data-library]');if(l){libraryFilter=l.dataset.library;$$('#library-filters .filter').forEach(x=>x.classList.toggle('active',x===l));library()}const i=e.target.closest('[data-open-idea]');if(i)openIdea(i.dataset.openIdea);const d=e.target.closest('[data-open-draft]');if(d)openDraft(d.dataset.openDraft);const k=e.target.closest('[data-open-case]');if(k)openCase(k.dataset.openCase);const p=e.target.closest('[data-open-production]');if(p)openProduction(p.dataset.openProduction);if(e.target.closest('[data-close-modal]'))closeModal();const c=e.target.closest('[data-copy]');if(c){const messages={approve:`Aprobá editorialmente ${c.dataset.id} sin cambios y comenzá la producción visual.`,changes:`Quiero pedir cambios editoriales en ${c.dataset.id}: `,'visual-approve':`Aprobá visualmente ${c.dataset.id} y marcala lista para publicar.`,'visual-changes':`Quiero pedir cambios visuales en ${c.dataset.id}: `};copy(messages[c.dataset.copy]||'')}});
      $('#global-search').addEventListener('input',e=>{query=e.target.value;render()});document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.clickable-row')){e.preventDefault();e.target.click();return}if(e.key==='/'&&document.activeElement!==$('#global-search')){e.preventDefault();$('#global-search').focus()}if(e.key==='Escape'&&!$('#detail-modal').hidden){closeModal();return}if(e.key==='Escape'){query='';$('#global-search').value='';render()}});$('#mobile-toggle').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#calendar-prev').addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);calendar()});$('#calendar-next').addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);calendar()});$('#calendar-today').addEventListener('click',()=>{calendarCursor=new Date(planHome.getFullYear(),planHome.getMonth(),1);calendar()});
      render();
    })();
  </script>
</body>
</html>
